services:
  apache:
    build:
      context: ../../..
      dockerfile: Docker/Dockerfile/Prod/Dockerfile.prod
    image: apache-dev
    container_name: apache_dev
    ports:
      - "8080:80"
    volumes:
      - ../../../connectFeelings:/usr/local/apache2/htdocs:ro
    restart: unless-stopped
